### PR TITLE
name-setter-run-at-start

### PR DESCRIPTION
**Pull request by ferrants**
Change-Id: I8628ab16952a394e8fd2f19becbec8e8051ee3e3

### CODE REVIEW

**Comment by ferrants** [comment]
Tested ✅ 
Updated this job with https://jenkins-staging.devaws.dataxu.net/job/jenkins-jobs_update_single_job/1284/
Job showing change: https://jenkins-staging.devaws.dataxu.net/job/jenkins-jobs_update_single_job/1285/

**Comment by pbuckley** [comment]
LGTM - I have this feeling that we're using an old branch of JJB that I pinned us to back when Ryan was trying to get his stuff merged upstream

**Comment by pbuckley** [comment]
yep, still pinned here: https://github.com/dataxu/jenkins-jobs/blob/master/bin/setup_virtualenv.sh#L10

**Comment by ferrants** [comment]
https://github.com/dataxu/jenkins-jobs/pull/1379 fixes that

**Pull request merged**
